jumpserver-dev/apps/jumpserver/urls.py
# ~*~ coding: utf-8 ~*~
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer

from .views import IndexView

schema_view = get_schema_view(title='Users API', renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer])
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^users/', include('users.urls.views_urls', namespace='users')),
    url(r'^assets/', include('assets.urls.views_urls', namespace='assets')),
    url(r'^perms/', include('perms.urls.views_urls', namespace='perms')),
    url(r'^audits/', include('audits.urls.views_urls', namespace='audits')),
    url(r'^applications/', include('applications.urls.views_urls', namespace='applications')),
    url(r'^ops/', include('ops.urls.view_urls', namespace='ops')),

    # Api url view map
    url(r'^api/users/', include('users.urls.api_urls', namespace='api-users')),
    url(r'^api/assets/', include('assets.urls.api_urls', namespace='api-assets')),
    url(r'^api/perms/', include('perms.urls.api_urls', namespace='api-perms')),
    url(r'^api/audits/', include('audits.urls.api_urls', namespace='api-audits')),
    url(r'^api/applications/', include('applications.urls.api_urls', namespace='api-applications')),
    url(r'^api/ops/', include('ops.urls.api_urls', namespace='api-ops')),
    url(r'^captcha/', include('captcha.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^docs/', schema_view, name="docs"),
    ]

jumpserver-dev/apps/audits/models.py
# -*- coding: utf-8 -*-
#

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


class LoginLog(models.Model):
    LOGIN_TYPE_CHOICE = (
        ('W', 'Web'),
        ('ST', 'SSH Terminal'),
        ('WT', 'Web Terminal')
    )

    username = models.CharField(max_length=20, verbose_name=_('Username'))
    name = models.CharField(max_length=20, blank=True, verbose_name=_('Name'))
    login_type = models.CharField(choices=LOGIN_TYPE_CHOICE, max_length=2,
                                  verbose_name=_('Login type'))
    login_ip = models.GenericIPAddressField(verbose_name=_('Login ip'))
    login_city = models.CharField(max_length=254, blank=True, null=True,
                                  verbose_name=_('Login city'))
    user_agent = models.CharField(max_length=254, blank=True, null=True,
                                  verbose_name=_('User agent'))
    date_login = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_('Date login'))

    class Meta:
        db_table = 'login_log'
        ordering = ['-date_login', 'username']


class ProxyLog(models.Model):
    LOGIN_TYPE_CHOICE = (
        ('ST', 'SSH Terminal'),
        ('WT', 'Web Terminal'),
    )

    user = models.CharField(max_length=32,  verbose_name=_('User'))
    asset = models.CharField(max_length=32, verbose_name=_('Asset'))
    system_user = models.CharField(max_length=32, verbose_name=_('System user'))
    login_type = models.CharField(
        choices=LOGIN_TYPE_CHOICE, max_length=2, blank=True,
        null=True, verbose_name=_('Login type'))
    terminal = models.CharField(
        max_length=32, blank=True, null=True, verbose_name=_('Terminal'))
    is_failed = models.BooleanField(
        default=False, verbose_name=_('Did connect failed'))
    is_finished = models.BooleanField(
        default=False, verbose_name=_('Is finished'))
    date_start = models.DateTimeField(
        auto_created=True, verbose_name=_('Date start'))
    date_finished = models.DateTimeField(
        null=True, verbose_name=_('Date finished'))

    def __unicode__(self):
        return '%s-%s-%s' % (self.user, self.asset, self.system_user)

    def commands(self):
        from audits.backends import command_store
        return command_store.filter(proxy_log_id=self.id)

    class Meta:
        ordering = ['-date_start', 'user']


class CommandLog(models.Model):
    proxy_log_id = models.IntegerField(db_index=True)
    user = models.CharField(max_length=48, db_index=True)
    asset = models.CharField(max_length=128, db_index=True)
    system_user = models.CharField(max_length=48, db_index=True)
    command_no = models.IntegerField()
    command = models.TextField(max_length=767, blank=True)
    output = models.TextField(blank=True)
    timestamp = models.FloatField(db_index=True)

    def __unicode__(self):
        return '%s: %s' % (self.id, self.command)

    class Meta:
        ordering = ['command_no', 'command']


class RecordLog(models.Model):
    proxy_log_id = models.IntegerField(db_index=True)
    output = models.TextField(verbose_name=_('Output'))
    timestamp = models.FloatField(db_index=True)

    def __unicode__(self):
        return 'Record: %s' % self.proxy_log_id

    class Meta:
        ordering = ['timestamp']

jumpserver-dev/apps/audits/views.py
# ~*~ coding: utf-8 ~*~
#
import time
from datetime import datetime

from django.views.generic import ListView, UpdateView, DeleteView, DetailView, TemplateView
from django.views.generic.edit import SingleObjectMixin
from django.utils.translation import ugettext as _
from django.utils import timezone
from django.utils.module_loading import import_string
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.conf import settings
from django.db.models import Q

from .models import ProxyLog, CommandLog, LoginLog
from .hands import User, Asset, SystemUser, AdminUserRequiredMixin
from audits.backends import command_store
from audits.backends import CommandLogSerializer


class ProxyLogListView(AdminUserRequiredMixin, ListView):
    model = ProxyLog
    template_name = 'audits/proxy_log_online_list.html'
    context_object_name = 'proxy_log_list'
    paginate_by = settings.CONFIG.DISPLAY_PER_PAGE
    keyword = username = hostname = system_user = date_from_s = date_to_s = ''
    ordering = ['is_finished', '-id']
    date_format = '%m/%d/%Y'

    def get_queryset(self):
        date_now = timezone.localtime(timezone.now())
        date_to_default = date_now.strftime(self.date_format)
        date_from_default = (date_now-timezone.timedelta(7))\
            .strftime(self.date_format)

        self.queryset = super(ProxyLogListView, self).get_queryset()
        self.keyword = self.request.GET.get('keyword', '')
        self.username = self.request.GET.get('username')
        self.ip = self.request.GET.get('ip')
        self.system_user = self.request.GET.get('system_user')
        self.date_from_s = self.request.GET.get('date_from', date_from_default)
        self.date_to_s = self.request.GET.get('date_to', date_to_default)

        filter_kwargs = {}
        if self.date_from_s:
            date_from = datetime.strptime(self.date_from_s, self.date_format)
            date_from = date_from.replace(tzinfo=timezone.get_current_timezone())
            filter_kwargs['date_start__gt'] = date_from
        if self.date_to_s:
            date_to = timezone.datetime.strptime(
                self.date_to_s + ' 23:59:59', '%m/%d/%Y %H:%M:%S')
            date_to = date_to.replace(tzinfo=timezone.get_current_timezone())
            filter_kwargs['date_start__lt'] = date_to
        if self.username:
            filter_kwargs['user'] = self.username
        if self.ip:
            filter_kwargs['asset'] = self.ip
        if self.system_user:
            filter_kwargs['system_user'] = self.system_user
        if self.keyword:
            self.queryset = self.queryset.filter(
                Q(user__icontains=self.keyword) |
                Q(asset__icontains=self.keyword) |
                Q(system_user__icontains=self.keyword)).distinct()
        if filter_kwargs:
            self.queryset = self.queryset.filter(**filter_kwargs)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Audits'),
            'action': _('Proxy log list'),
            'user_list': set(
                list(ProxyLog.objects.values_list('user', flat=True))),
            'asset_list': set(
                list(ProxyLog.objects.values_list('asset', flat=True))),
            'system_user_list': set(
                list(ProxyLog.objects.values_list('system_user', flat=True))),
            'keyword': self.keyword,
            'date_from': self.date_from_s,
            'date_to': self.date_to_s,
            'username': self.username,
            'ip': self.ip,
            'system_user': self.system_user,
        }
        kwargs.update(context)
        return super(ProxyLogListView, self).get_context_data(**kwargs)


class ProxyLogOfflineListView(ProxyLogListView):
    template_name = 'audits/proxy_log_offline_list.html'

    def get_queryset(self):
        queryset = super(ProxyLogOfflineListView, self).get_queryset()
        queryset = queryset.filter(is_finished=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = {
            'action': _('Proxy log offline list'),
        }
        kwargs.update(context)
        return super(ProxyLogOfflineListView, self).get_context_data(**kwargs)


class ProxyLogOnlineListView(ProxyLogListView):
    template_name = 'audits/proxy_log_online_list.html'

    def get_queryset(self):
        queryset = super(ProxyLogOnlineListView, self).get_queryset()
        queryset = queryset.filter(is_finished=False)
        return queryset

    def get_context_data(self, **kwargs):
        context = {
            'action': _('Proxy log online list'),
        }
        kwargs.update(context)
        return super(ProxyLogOnlineListView, self).get_context_data(**kwargs)


class ProxyLogDetailView(AdminUserRequiredMixin,
                         SingleObjectMixin,
                         ListView):
    template_name = 'audits/proxy_log_detail.html'
    context_object_name = 'proxy_log'
    object = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=ProxyLog.objects.all())
        return super(ProxyLogDetailView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return list(command_store.filter(proxy_log_id=self.object.id))

    def get_context_data(self, **kwargs):
        context = {
            'app': 'Audits',
            'action': 'Proxy log detail',
        }
        kwargs.update(context)
        return super(ProxyLogDetailView, self).get_context_data(**kwargs)


# class ProxyLogCommandsListView(AdminUserRequiredMixin,
#                                SingleObjectMixin,
#                                ListView):
#     template_name = 'audits/proxy_log_commands_list_modal.html'
#     object = ''
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object(queryset=ProxyLog.objects.all())
#         return super(ProxyLogCommandsListView, self).\
#             get(request, *args, **kwargs)
#
#     def get_queryset(self):
#         return list(self.object.command_log.all())


class CommandLogListView(AdminUserRequiredMixin, ListView):
    template_name = 'audits/command_log_list.html'
    paginate_by = settings.CONFIG.DISPLAY_PER_PAGE
    context_object_name = 'command_list'
    username = ip = system_user = command = date_from_s = date_to_s = ''
    date_format = '%m/%d/%Y'
    ordering = ['-id']

    def get_queryset(self):
        date_now = timezone.localtime(timezone.now())
        date_to_default = date_now.strftime(self.date_format)
        date_from_default = (date_now - timezone.timedelta(7)) \
            .strftime(self.date_format)
        self.command = self.request.GET.get('command', '')
        self.username = self.request.GET.get('username')
        self.ip = self.request.GET.get('ip')
        self.system_user = self.request.GET.get('system_user')
        self.date_from_s = \
            self.request.GET.get('date_from', date_from_default)
        self.date_to_s = \
            self.request.GET.get('date_to', date_to_default)

        filter_kwargs = {}
        if self.date_from_s:
            date_from = datetime.strptime(self.date_from_s, self.date_format)\
                .replace(tzinfo=timezone.get_current_timezone())
            # date_from_utc = date_from.astimezone(pytz.utc)
            date_from_ts = time.mktime(date_from.timetuple())
            filter_kwargs['date_from_ts'] = date_from_ts
        if self.date_to_s:
            date_to = datetime.strptime(
                self.date_to_s + ' 23:59:59', '%m/%d/%Y %H:%M:%S')\
                .replace(tzinfo=timezone.get_current_timezone())
            date_to_ts = time.mktime(date_to.timetuple())
            filter_kwargs['date_to_ts'] = date_to_ts
        if self.username:
            filter_kwargs['user'] = self.username
        if self.ip:
            filter_kwargs['asset'] = self.ip
        if self.system_user:
            filter_kwargs['system_user'] = self.system_user
        if self.command:
            filter_kwargs['command'] = self.command
        self.queryset = command_store.filter(**filter_kwargs).order_by(*self.ordering)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Audits'),
            'action': _('Command log list'),
            'user_list': User.objects.all().order_by('username'),
            'asset_list': Asset.objects.all().order_by('ip'),
            'system_user_list': SystemUser.objects.all().order_by('username'),
            'command': self.command,
            'date_from': self.date_from_s,
            'date_to': self.date_to_s,
            'username': self.username,
            'ip': self.ip,
            'system_user': self.system_user,
        }
        kwargs.update(context)
        return super(CommandLogListView, self).get_context_data(**kwargs)


class LoginLogListView(AdminUserRequiredMixin, ListView):
    model = LoginLog
    paginate_by = settings.CONFIG.DISPLAY_PER_PAGE
    template_name = 'audits/login_log_list.html'
    context_object_name = 'login_log_list'
    keyword = username = date_from_s = date_to_s = ''

    def get_queryset(self):
        date_now = timezone.localtime(timezone.now())
        now_s = date_now.strftime('%m/%d/%Y')
        seven_days_ago_s = (date_now - timezone.timedelta(7))\
            .strftime('%m/%d/%Y')
        self.queryset = super(LoginLogListView, self).get_queryset()
        self.keyword = keyword = self.request.GET.get('keyword', '')
        self.username = username = self.request.GET.get('username', '')
        self.date_from_s = date_from_s = self.request.GET.get(
            'date_from', '%s' % seven_days_ago_s)
        self.date_to_s = date_to_s = self.request.GET.get(
            'date_to', '%s' % now_s)

        if date_from_s:
            date_from = timezone.datetime.strptime(date_from_s, '%m/%d/%Y')
            self.queryset = self.queryset.filter(date_login__gt=date_from)
        if date_to_s:

jumpserver-dev/apps/audits/templates/audits/command_log_list.html
{% extends '_base_list.html' %}
{% load i18n %}
{% load static %}
{% load common_tags %}
{% block content_left_head %}
    <link href="{% static "css/plugins/footable/footable.core.css" %}" rel="stylesheet">
    <link href="{% static 'css/plugins/datepicker/datepicker3.css' %}" rel="stylesheet">
    <style>
        #search_btn {
            margin-bottom: 0;
        }
    </style>
{% endblock %}

{% block table_search %}
    <form id="search_form" method="get" action="" class="pull-right form-inline">
        <div class="form-group" id="date">
            <div class="input-daterange input-group" id="datepicker">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input type="text" class="input-sm form-control" style="width: 100px;" name="date_from" value="{{ date_from }}">
                <span class="input-group-addon">to</span>
                <input type="text" class="input-sm form-control" style="width: 100px;" name="date_to" value="{{ date_to }}">
            </div>
        </div>
        <div class="input-group">
            <select class="select2 form-control" name="username">
                <option value="">{% trans 'User' %}</option>
                {% for u in user_list %}
                    <option value="{{ u.username }}" {% if username == u.username %} selected {% endif %}>{{ u.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group">
            <select class="select2 form-control" name="ip">
                <option value="">{% trans 'Asset' %}</option>
                {% for a in asset_list %}
                    <option value="{{ a.ip }}" {% if ip == a.ip %} selected {% endif %}>{{ a.ip }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group">
            <select class="select2 form-control" name="system_user">
                <option value="">{% trans 'System user' %}</option>
                {% for s in system_user_list %}
                    <option value="{{ s.username }}" {% if s.username == system_user %} selected {% endif %}>{{ s.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group">
            <input type="text" class="form-control input-sm" name="command" placeholder="Command" value="{{ command }}">
        </div>
        <div class="input-group">
            <div class="input-group-btn">
                <button id='search_btn' type="submit" class="btn btn-sm btn-primary">
                    搜索
                </button>
            </div>
        </div>
    </form>
{% endblock %}
{% block table_container %}
    <table class="footable table table-stripped toggle-arrow-tiny" data-page="false">
        <thead>
        <tr>
            <th data-toggle="true">ID</th>
            <th>Command</th>
            <th>Username</th>
            <th>IP</th>
            <th>System user</th>
            <th>Proxy log</th>
            <th>Datetime</th>
            <th data-hide="all">Output</th>
        </tr>
        </thead>
        <tbody>
        {% for command in command_list %}
            <tr>
                <td>{{ command.id }}</td>
                <td>{{ command.command }}</td>
                <td>{{ command.user }}</td>
                <td>{{ command.asset }}</td>
                <td>{{ command.system_user }}</td>
                <td><a href="{% url 'audits:proxy-log-detail' pk=command.proxy_log_id  %}">{{ command.proxy_log_id}}</a></td>
                <td>{{ command.timestamp|ts_to_date }}</td>
                <td><pre style="border: none; background: none">{{ command.output|to_html|safe }}</pre></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block custom_foot_js %}
    <script src="{% static "js/plugins/footable/footable.all.min.js" %}"></script>
    <script src="{% static 'js/plugins/datepicker/bootstrap-datepicker.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.footable').footable();
            $('.select2').select2();
            $('#date .input-daterange').datepicker({
                dateFormat: 'mm/dd/yy',
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });
        });
    </script>
{% endblock %}

jumpserver-dev/apps/audits/templates/audits/login_log_list.html
{% extends '_base_list.html' %}
{% load i18n %}
{% load static %}
{% load common_tags %}
{% block content_left_head %}
    <link href="{% static 'css/plugins/datepicker/datepicker3.css' %}" rel="stylesheet">
    <style>
        #search_btn {
            margin-bottom: 0;
        }
    </style>
{% endblock %}


{% block table_search %}
    <form id="search_form" method="get" action="" class="pull-right form-inline">
        <div class="form-group" id="date">
            <div class="input-daterange input-group" id="datepicker">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input type="text" class="input-sm form-control" style="width: 100px;" name="date_from" value="{{ date_from }}">
                <span class="input-group-addon">to</span>
                <input type="text" class="input-sm form-control" style="width: 100px;" name="date_to" value="{{ date_to }}">
            </div>
        </div>
        <div class="input-group">
            <select class="select2 form-control" name="username">
                <option value="">{% trans 'Select user' %}</option>
                {% for user in user_list %}
                    <option value="{{ user.username }}" {% if user.username == username %} selected {% endif %}>{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group">
            <input type="text" class="form-control input-sm" name="keyword" placeholder="Search" value="{{ keyword }}">
        </div>
        <div class="input-group">
            <div class="input-group-btn">
                <button id='search_btn' type="submit" class="btn btn-sm btn-primary">
                    搜索
                </button>
            </div>
        </div>
    </form>
{% endblock %}

{% block table_head %}
    <th class="text-center">{% trans 'ID' %}</th>
    <th class="text-center">{% trans 'Username' %}</th>
    <th class="text-center">{% trans 'Name' %}</th>
    <th class="text-center">{% trans 'Type' %}</th>
    <th class="text-center">{% trans 'UA' %}</th>
    <th class="text-center">{% trans 'IP' %}</th>
    <th class="text-center">{% trans 'City' %}</th>
    <th class="text-center">{% trans 'Date' %}</th>
{% endblock %}

{% block table_body %}
    {% for login_log in login_log_list %}
        <tr class="gradeX">
            <td class="text-center">
                {{ login_log.id }}
{#                <a href="{% url 'audits:proxy-log-detail' pk=login_log.id %}">{{ login_log.id }}</a>#}
            </td>
            <td class="text-center">{{ login_log.username }}</td>
            <td class="text-center">{{ login_log.name }}</td>
            <td class="text-center">{{ login_log.get_login_type_display }}</td>
            {% if login_log.login_type == 'W' %}
                <td class="text-center">
                    <span href="javascript:void(0);" data-toggle="tooltips" title="{{ login_log.user_agent  }}">{{ login_log.user_agent | truncatechars:20 }}</span>
                </td>
            {% else %}
                <td class="text-center">{{ login_log.terminal }}</td>
            {% endif %}
            <td class="text-center">{{ login_log.login_ip }}</td>
            <td class="text-center">{{ login_log.login_city }}</td>
            <td class="text-center">{{ login_log.date_login }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block custom_foot_js %}
    <script src="{% static 'js/plugins/datepicker/bootstrap-datepicker.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('table').DataTable({
                "searching": false,
                "bInfo" : false,
                "paging": false,
                "order": []
            });
            $('#date .input-daterange').datepicker({
                dateFormat: 'mm/dd/yy',
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });
            $('.select2').select2();
        })
    </script>
{% endblock %}

jumpserver-dev/apps/audits/templates/audits/proxy_log_commands_list_modal.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    {% include '_head_css_js.html' %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static "css/plugins/footable/footable.core.css" %}" rel="stylesheet">
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/plugins/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="tab-content">
<div class="ibox-content">
    <input type="text" class="form-control input-sm m-b-xs" id="filter"
                                   placeholder="Search in table">
    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="10" data-filter=#filter>
        <thead>
        <tr>
            <th data-toggle="true">ID</th>
            <th>Command</th>
            <th data-hide="all">Output</th>
            <th>Datetime</th>
        </tr>
        </thead>
        <tbody class="table_body">
        {% for command in object_list %}
            <tr>
                <td>{{ command.command_no }}</td>
                <td>{{ command.command }}</td>
                <td>{{ command.output_decode |safe }}</td>
                <td>{{ command.datetime }}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5">
                    <ul class="pagination pull-right"></ul>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
</div>
</div>
</body>
<script src="{% static "js/plugins/footable/footable.all.min.js" %}"></script>
<script>
    $(document).ready(function () {
        $('.footable').footable();
    });
</script>
</html>

jumpserver-dev/apps/audits/templates/audits/proxy_log_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load common_tags %}

{% block custom_head_css_js %}
    <link href="{% static "css/plugins/footable/footable.core.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#" class="text-center"> {% trans 'Proxy log detail' %} </a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="col-sm-11" style="padding-left: 0;">
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <span style="float: left">{% trans 'Command log list' %} <b>{{ user_object.name }}</b></span>
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            <i class="fa fa-wrench"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown-user">
                                        </ul>
                                        <a class="close-link">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="ibox-content">
                                    <table id="command-log" class="footable table table-stripped toggle-arrow-tiny" data-page-size="10">
                                        <thead>
                                        <tr>
                                            <th data-toggle="true">ID</th>
                                            <th>Command</th>
                                            <th data-hide="all">Output</th>
                                            <th>Datetime</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for command in object_list %}
                                            <tr>
                                                <td>{{ command.command_no }}</td>
                                                <td>{{ command.command }}</td>
                                                <td><pre style="border: none;background: none">{{ command.output|to_html|safe}}</pre></td>
                                                <td>{{ command.timestamp|ts_to_date}}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <td colspan="5">
                                                    <ul class="pagination pull-right"></ul>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block custom_foot_js %}
    <script src="{% static "js/plugins/footable/footable.all.min.js" %}"></script>
    <script>
        $(document).ready(function () {
            $('.footable').footable();
        });
    </script>
{% endblock %}